<?php

namespace TiDB\Grammars;

use Illuminate\Database\Connection;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Schema\Grammars\MySqlGrammar;
use Illuminate\Support\Fluent;

class SchemaGrammar extends MySqlGrammar
{
    /**
     * TiDB does not support multiple schema changes in one statement.
     * @param Blueprint $blueprint
     * @param Fluent $command
     * @return array|string
     */
    public function compileAdd(Blueprint $blueprint, Fluent $command)
    {
        $columns = $this->prefixArray('add', $this->getColumns($blueprint));
        $addStatements = [];
        foreach ($columns as $column) {
            $addStatements[] = 'alter table ' . $this->wrapTable($blueprint) . ' ' . $column;
        }

        return $addStatements;
    }


    /**
     * Compile a drop column command. TiDB does not support multiple schema changes in one statement. 
     * @param \Illuminate\Database\Schema\Blueprint $blueprint
     * @param \Illuminate\Support\Fluent $command
     * @return string|array
     */
    public function compileDropColumn(Blueprint $blueprint, Fluent $command)
    {
        $columns = $this->prefixArray('drop', $this->wrapArray($command->columns));
        $dropStatements = [];

        foreach ($columns as $column) {
            $dropStatements[] = 'alter table ' . $this->wrapTable($blueprint) . ' ' . $column;
        }

        return $dropStatements;
    }

    /**
     * @param Blueprint $blueprint
     * @param Fluent $command
     * @param Connection $connection
     * @return array
     */
    public function compileChange(Blueprint $blueprint, Fluent $command, Connection $connection)
    {
        $compiled_change = parent::compileChange($blueprint, $command, $connection); // TODO: Change the autogenerated stub
        if (is_array($compiled_change)) {
            //TODO: filter / update change DDL's here.
            return $compiled_change;
        }

        return [];
    }

    public function compileForeign(Blueprint $blueprint, Fluent $command)
    {
        //return parent::compileForeign($blueprint, $command); // TODO: Change the autogenerated stub
        return []; //no foreign keys in our db at all! TiDB does not suppoert Foreign Keys. :)
    }
}
